name: socilo_reply
description: Smart Comment Moderation App for Instagram
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase for backend
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  
  # State management
  provider: ^6.0.5
  
  # HTTP requests
  http: ^1.1.0
  
  # UI components
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
